version: 0.2

phases:
  install:
    commands:
      - echo Installing Meteor
      - curl https://install.meteor.com/ | sh
  pre_build:
    commands:
      - echo Displaying folder structure
      - ls
  build:
    commands:
      - echo Build started on `date`
      - cd src && npm install --production
      - meteor build .. --allow-superuser --directory
      - cd ../bundle/programs/server && npm install
  post_build:
    commands:
      - cd ../../../
      - echo Build completed on `date`
artifacts:
  base-directory: bundle # Bundle contains the built code
  files:
    - ./**/* # Include all files